export { lightTheme } from './light'
export { darkTheme } from './dark'
export { generateCustomTheme, mergeTheme } from './utils'

// Custom themes
export { lightGreenTheme, darkGreenTheme } from './green'
export { lightBlueTheme, darkBlueTheme } from './blue'
export { lightPurpleTheme, darkPurpleTheme } from './purple'
export { lightOrangeTheme, darkOrangeTheme } from './orange'
export { lightIndigoTheme, darkIndigoTheme } from './indigo'
export { lightTealTheme, darkTealTheme } from './teal'
export { lightPinkTheme, darkPinkTheme } from './pink'
export { lightRedTheme, darkRedTheme } from './red'
export { lightYellowTheme, darkYellowTheme } from './yellow'
export { lightBrownTheme, darkBrownTheme } from './brown'
